# Generated by Django 6.0.2 on 2026-04-09 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_f_name_alter_user_l_name_and_more'),
        ('professors', '0014_institutiondomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='professors.institution'),
        ),
    ]
