<script setup>
    import { ref, onMounted, onUnmounted } from 'vue'
    import api from "@/api/axios"

    const props = defineProps({
        professor_id: Number
    })
    const displayedHtml = ref('');
    const showCredit = ref(false);
    let timer = null;
    onMounted(async () => {
        try {
            const res = await api.get(`/overviews/${props.professor_id}`)
            console.log(res)
            startTypewriter(res.data.overview);
        } catch (error) {
            startTypewriter("Overview Unavailable.");
        }
    })

    const startTypewriter = async (text) => {
        if (timer) clearInterval(timer);
        displayedHtml.value = '';

        const words = text.split(' ');
        let currentMarkdown = '';
        let i = 0;

        timer = setInterval(() => {
            if (i < words.length) {
                currentMarkdown += words[i] + ' ';
                const rawHtml = marked.parse(currentMarkdown);
                displayedHtml.value = rawHtml;
                i++;
            } else {
                clearInterval(timer);
                showCredit.value = true;
            }
        }, 40);
    };

    onUnmounted(() => {
        if (timer) clearInterval(timer);
    });
</script>

<template>
    <div class="bg-card shadow rounded-xl p-[18px] flex flex-col text-text-main text-left max-w-300 overflow-hidden relative pb-10">
        <h3 class="text-2xl font-bold inline text-primary">AI Overview</h3>
        <div v-html="displayedHtml" class="text-text-main block">

        </div>
        <p class="text-text-muted text-right text-sm bottom-2 right-4 absolute" v-if="showCredit">Generated by Gemma:12b</p>
    </div>
</template>