<script setup>
    import { ref, onMounted, onUnmounted, watch } from 'vue'
    import api from "@/api/axios"

    const props = defineProps({
        professor_id: Number
    })
    const displayedHtml = ref('');
    const showCredit = ref(false);
    let timer = null;
    onMounted(async () => {
        fetchOverview();
    })

    async function fetchOverview(params) {
        try {
            const res = await api.get(`/overviews/${props.professor_id}`)
            console.log(res)
            startTypewriter(res.data.overview);
        } catch (error) {
            startTypewriter("Overview Unavailable.");
        }
    }

    watch(() => props.professor_id, (newId, oldId) => {
        fetchOverview();
    })

    const startTypewriter = async (text) => {
        if (timer) clearInterval(timer);
        displayedHtml.value = '';

        const words = text.replace(/\n/g, "<br>").split(' ');
        let currentMarkdown = '';
        let i = 0;

        timer = setInterval(() => {
            if (i < words.length) {
                currentMarkdown += words[i] + ' ';
                const rawHtml = marked.parse(currentMarkdown);
                displayedHtml.value = rawHtml;
                i++;
            } else {
                clearInterval(timer);
                showCredit.value = true;
            }
        }, 40);
    };

    onUnmounted(() => {
        if (timer) clearInterval(timer);
    });
</script>

<template>
    <div class="bg-card shadow-md rounded-xl p-[18px] flex flex-col text-text-main text-left overflow-hidden relative pb-10 border border-gray-100 h-full">
        
        <div class="flex items-center gap-2 mb-2">
            <h3 class="text-xl font-bold text-primary">AI Overview</h3>
        </div>

        <div v-html="displayedHtml" class="text-text-main text-sm leading-relaxed prose prose-sm max-w-none">
            </div>

        <p class="text-text-muted opacity-60 text-right text-[10px] bottom-3 right-4 absolute font-medium uppercase tracking-tighter" v-if="showCredit">
            Generated by Gemma:12b
        </p>
    </div>
</template>