# Generated by Django 6.0.2 on 2026-02-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professor_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=32)),
                ('l_name', models.CharField(max_length=32)),
                ('m_name', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
