# Generated by Django 6.0.2 on 2026-03-07 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_institution_course_professorcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='professors.institution'),
        ),
    ]
