# Generated by Django 6.0.2 on 2026-03-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_professor_institution'),
        ('professors', '0004_reviewvote'),
    ]

    operations = [
    ]
