# Generated by Django 6.0.2 on 2026-03-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_merge_0004_professor_institution_0004_reviewvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='helpful_count',
        ),
    ]
