# Generated by Django 6.0.2 on 2026-03-13 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_remove_review_helpful_count'),
        ('professors', '0007_alter_reviewreport_reporter'),
    ]

    operations = [
    ]
