# Generated by Django 6.0.2 on 2026-03-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0008_merge_20260313_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
