# Generated by Django 6.0.2 on 2026-03-31 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0011_tag_remove_professor_institution_reviewtag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fave_prof', to='professors.professor')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fave_prof', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('professor_id', 'student_id')},
            },
        ),
    ]
