# Generated by Django 6.0.2 on 2026-03-31 05:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0012_favoriteprof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteprof',
            old_name='professor_id',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='favoriteprof',
            old_name='student_id',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='favoriteprof',
            unique_together={('professor', 'student')},
        ),
    ]
