# Generated by Django 6.0.2 on 2026-04-09 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0013_rename_professor_id_favoriteprof_professor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=32)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domains', to='professors.institution')),
            ],
        ),
    ]
