# Generated by Django 6.0.2 on 2026-04-09 22:04

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0014_institutiondomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiondomain',
            name='domain',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AddConstraint(
            model_name='institutiondomain',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('domain'), name='unique_domain'),
        ),
    ]
