# Generated by Django 6.0.2 on 2026-04-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0015_alter_institutiondomain_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='domain',
        ),
    ]
