# Generated by Django 6.0.2 on 2026-04-12 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0016_remove_institution_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('overview', models.TextField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='professors.professor', unique=True)),
            ],
        ),
    ]
