# Generated by Django 6.0.2 on 2026-04-13 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0017_professoroverview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professoroverview',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='professors.professor'),
        ),
    ]
