# Generated by Django 6.0.2 on 2026-04-13 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0018_alter_professoroverview_professor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_course', to='professors.course'),
        ),
        migrations.AddField(
            model_name='review',
            name='semester_term',
            field=models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('summer', 'Summer')], default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='semester_year',
            field=models.CharField(default=-1, max_length=9),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('student', 'professor', 'course', 'semester_term', 'semester_year')},
        ),
    ]
